### ISSUE TITLE
Migrate to CD ?

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/pipeline-library#895]
### What feature do you want to see added?

Hi,

Should this repo migrated to CD ?

Release are confusing, the last one is 2.0 from 2020.

Perhaps we could have CD and pointing to the tag instead of a moving branch ? (with an updatecli manifest to bump the `defaultVersion`  of the JcasC config on different controller config

By using a tag we can also avoid checking out the library each time and setup caching on the controller 

On the JCasC

```yaml
cachingConfiguration:
  excludedVersionsStr: "master main feature/ release/ bugfix/ hotfix/ pull/"
  refreshTimeMinutes: 86400
```
